name: "django_stickers_bot"

services:
  postgres:
    image: postgres:16
    container_name: postgres_for_bot
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    volumes:
      - ./for_docker/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER}" ]
      interval: 1s
      timeout: 3s
      retries: 3

  django_stickers_bot:
    build: .
    container_name: django_stickers_bot
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./for_docker/fixtures:/django_stickers_bot/fixtures
    depends_on:
      postgres:
        condition: service_healthy