# Generated by Django 5.2.17 on 2026-09-27 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_add_extension__custom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sticker",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="stickerset",
            options={"ordering": ("id",)},
        ),
    ]
